name: 'Generate PR Summary'
description: 'Generate a summary of build and test results for PRs'
inputs:
  include-coverage:
    description: 'Include code coverage in summary'
    required: false
    default: 'true'
  test-results-directory:
    description: 'Directory containing test results'
    required: false
    default: 'TestResults'
  build-status:
    description: 'Build status (success or failure)'
    required: false
    default: 'success'
  project-name:
    description: 'Project or solution name'
    required: false
    default: ''
outputs:
  markdown:
    description: 'Markdown content of the generated PR summary'
    value: ${{ steps.generate.outputs.content }}
runs:
  using: 'composite'
  steps:
    - name: Parse test results
      id: test-results
      shell: bash
      run: |
        set -euo pipefail
        
        # Parse TRX files for actual test counts
        TOTAL=0
        PASSED=0
        FAILED=0
        SKIPPED=0
        
        if [ -d "${{ inputs.test-results-directory }}" ]; then
          # Use find instead of globstar pattern
          while IFS= read -r trx; do
            if [ -f "$trx" ]; then
              # Parse TRX XML for test counts (first occurrence only)
              T=$(grep -o '<Counters total="[0-9]*"' "$trx" | head -n1 | grep -o '[0-9]*' || echo 0)
              P=$(grep -o 'passed="[0-9]*"' "$trx" | head -n1 | grep -o '[0-9]*' || echo 0)
              F=$(grep -o 'failed="[0-9]*"' "$trx" | head -n1 | grep -o '[0-9]*' || echo 0)
              TOTAL=$((TOTAL + T))
              PASSED=$((PASSED + P))
              FAILED=$((FAILED + F))
            fi
          done < <(find "${{ inputs.test-results-directory }}" -type f -name "*.trx")
          SKIPPED=$((TOTAL - PASSED - FAILED))
        fi
        
        echo "total=$TOTAL" >> $GITHUB_OUTPUT
        echo "passed=$PASSED" >> $GITHUB_OUTPUT
        echo "failed=$FAILED" >> $GITHUB_OUTPUT
        echo "skipped=$SKIPPED" >> $GITHUB_OUTPUT
    
    - name: Parse coverage results
      id: coverage
      if: ${{ inputs.include-coverage == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        
        # Parse coverage from Cobertura XML
        COVERAGE="N/A"
        if [ -d "${{ inputs.test-results-directory }}" ]; then
          COV_FILE=$(find "${{ inputs.test-results-directory }}" -type f -name "coverage.cobertura.xml" | head -n 1)
          if [ -n "$COV_FILE" ] && [ -f "$COV_FILE" ]; then
            # Extract line-rate (should be between 0 and 1)
            LINE_RATE=$(grep -o 'line-rate="[0-9.]*"' "$COV_FILE" | head -n1 | grep -o '[0-9.]*' || echo "")
            if [ -n "$LINE_RATE" ] && [ "$LINE_RATE" != "0" ]; then
              # Validate it's a valid decimal and convert to percentage
              COVERAGE=$(awk "BEGIN {rate=$LINE_RATE; if (rate >= 0 && rate <= 1) printf \"%.1f\", rate * 100; else print \"N/A\"}")
            fi
          fi
        fi
        echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
    
    - name: Generate PR summary
      id: generate
      shell: bash
      run: |
        set -euo pipefail
        
        # Build the markdown content once and both write to step summary and set as an output
        TOTAL="${{ steps.test-results.outputs.total }}"
        PASSED="${{ steps.test-results.outputs.passed }}"
        FAILED="${{ steps.test-results.outputs.failed }}"
        SKIPPED="${{ steps.test-results.outputs.skipped }}"
        
        TOTAL=${TOTAL:-0}
        PASSED=${PASSED:-0}
        FAILED=${FAILED:-0}
        SKIPPED=${SKIPPED:-0}
        
        {
          echo "## :rocket: PR Validation Summary"
          echo ""
          
          if [ "${{ inputs.build-status }}" = "success" ]; then
            echo "### :white_check_mark: Build: **Passed**"
          else
            echo "### :x: Build: **Failed**"
          fi
          echo ""
          
          if [ "$TOTAL" -gt 0 ]; then
            echo "### :test_tube: Tests: $PASSED / $TOTAL passed"
            echo ""
            echo "| Status | Count |"
            echo "|--------|-------|"
            echo "| :white_check_mark: Passed | $PASSED |"
            if [ "$FAILED" -gt 0 ]; then
              echo "| :x: Failed | $FAILED |"
            fi
            if [ "$SKIPPED" -gt 0 ]; then
              echo "| :next_track_button: Skipped | $SKIPPED |"
            fi
            echo ""
          else
            echo "### :test_tube: Tests: No tests found"
            echo ""
          fi
          
          if [ "${{ inputs.include-coverage }}" = "true" ]; then
            COVERAGE="${{ steps.coverage.outputs.coverage }}"
            if [ -n "$COVERAGE" ] && [ "$COVERAGE" != "N/A" ]; then
              echo "### :bar_chart: Code Coverage: ${COVERAGE}%"
              echo ""
            fi
          fi
          
          echo "### :information_source: Details"
          echo "- **Commit:** \`${{ github.sha }}\`"
          echo "- **Branch:** \`${{ github.ref_name }}\`"
          echo "- **Triggered by:** @${{ github.actor }}"
          if [ -n "${{ inputs.project-name }}" ]; then
            echo "- **Project:** ${{ inputs.project-name }}"
          fi
          echo ""
          echo "---"
          echo "_View detailed logs in the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})_"
        } > summary.md
        
        # Write to the PR summary panel
        cat summary.md >> $GITHUB_STEP_SUMMARY
        
        # Set as output
        {
          echo "content<<EOF"
          cat summary.md
          echo "EOF"
        } >> $GITHUB_OUTPUT
