name: 'Restore .NET Dependencies'
description: 'Restore NuGet packages for .NET projects'
inputs:
  working-directory:
    description: 'Working directory for restore'
    required: false
    default: '.'
  verbosity:
    description: 'Restore verbosity level'
    required: false
    default: 'minimal'
runs:
  using: 'composite'
  steps:
    - name: Restore dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: dotnet restore --verbosity ${{ inputs.verbosity }}
