name: 'Pack .NET Project'
description: 'Create NuGet packages from .NET projects'
inputs:
  project-path:
    description: 'Path to the project to pack'
    required: false
    default: '.'
  configuration:
    description: 'Build configuration'
    required: false
    default: 'Release'
  output-directory:
    description: 'Output directory for packages'
    required: false
    default: './artifacts'
  version:
    description: 'Full version to override (e.g., 1.2.3). Cannot be used with version-suffix.'
    required: false
    default: ''
  version-suffix:
    description: 'Version suffix to append (e.g., beta.1). Cannot be used with version.'
    required: false
    default: ''
  no-build:
    description: 'Skip build during pack'
    required: false
    default: 'false'
  working-directory:
    description: 'Working directory for pack'
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
    - name: Pack project
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Validate that version and version-suffix are not both set
        if [ -n "${{ inputs.version }}" ] && [ -n "${{ inputs.version-suffix }}" ]; then
          echo "::error::Cannot specify both 'version' and 'version-suffix'. Use 'version' for full version override (e.g., 1.2.3) or 'version-suffix' to append to existing version (e.g., beta.1)."
          exit 1
        fi
        
        ARGS="${{ inputs.project-path }} --configuration ${{ inputs.configuration }} --output ${{ inputs.output-directory }}"
        
        if [ "${{ inputs.no-build }}" == "true" ]; then
          ARGS="$ARGS --no-build"
        fi
        
        if [ -n "${{ inputs.version }}" ]; then
          ARGS="$ARGS /p:Version=${{ inputs.version }}"
        fi
        
        if [ -n "${{ inputs.version-suffix }}" ]; then
          ARGS="$ARGS --version-suffix ${{ inputs.version-suffix }}"
        fi
        
        dotnet pack $ARGS
