name: 'Add NuGet Source'
description: 'Add a custom NuGet source to the configuration'
inputs:
  source-name:
    description: 'Name for the NuGet source'
    required: true
  source-url:
    description: 'URL for the NuGet source'
    required: true
  username:
    description: 'Username for authenticated feeds'
    required: false
    default: ''
  password:
    description: 'Password or token for authenticated feeds'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Add NuGet source
      shell: bash
      run: |
        if [ -n "${{ inputs.username }}" ] && [ -n "${{ inputs.password }}" ]; then
          dotnet nuget add source ${{ inputs.source-url }} --name ${{ inputs.source-name }} --username ${{ inputs.username }} --password ${{ inputs.password }} --store-password-in-clear-text
        else
          dotnet nuget add source ${{ inputs.source-url }} --name ${{ inputs.source-name }}
        fi
