name: Build and Test

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Linux
    uses: ./.github/workflows/templates/jobs/build-and-test.yml
    with:
      dotnet-version: '10.0.x'
      configuration: 'Release'
      runs-on: 'ubuntu-latest'
      enable-cache: true
      collect-coverage: true
  
  build-windows:
    name: Build on Windows
    uses: ./.github/workflows/templates/jobs/build-and-test.yml
    with:
      dotnet-version: '10.0.x'
      configuration: 'Release'
      runs-on: 'windows-latest'
      enable-cache: true
      collect-coverage: true
  
  build-macos:
    name: Build on macOS
    uses: ./.github/workflows/templates/jobs/build-and-test.yml
    with:
      dotnet-version: '10.0.x'
      configuration: 'Release'
      runs-on: 'macos-latest'
      enable-cache: true
      collect-coverage: true
