# Example: Complete publish workflow for external repository with version override
# This ensures the git tag version is used for all packages, regardless of .csproj versions

name: Publish to NuGet

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (without v prefix, e.g., 0.1.1)'
        required: true
        type: string

# Required permissions for publishing and creating releases
permissions:
  contents: write        # For creating GitHub releases
  packages: write        # For publishing to NuGet
  id-token: write        # For OIDC authentication (optional)

jobs:
  # Step 1: Extract version from git tag or manual input
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      version-tag: ${{ steps.get_version.outputs.version-tag }}
    steps:
      - name: Determine version
        id: get_version
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
            VERSION_TAG="v${VERSION}"
          else
            VERSION="${GITHUB_REF#refs/tags/v}"
            VERSION_TAG="v${VERSION}"
          fi
          echo "version=$VERSION" >>"$GITHUB_OUTPUT"
          echo "version-tag=$VERSION_TAG" >>"$GITHUB_OUTPUT"
          echo "Publishing version: $VERSION"

  # Step 2: Build, test, pack, and publish using reusable workflow
  release:
    name: Build, Pack & Publish
    needs: prepare
    uses: HoneyDrunkStudios/HoneyDrunk.Actions/.github/workflows/dotnet-library-release.yml@main
    with:
      dotnet-version: '9.0.x'
      configuration: 'Release'
      runs-on: 'ubuntu-latest'
      working-directory: '.'
      project-path: 'HoneyDrunk.Standards/HoneyDrunk.Standards.csproj'
      package-version: ${{ needs.prepare.outputs.version }}  # ? IMPORTANT: Override version from git tag
      nuget-source: 'https://api.nuget.org/v3/index.json'
      skip-duplicate: true
      actions-ref: 'main'
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}

  # Step 3: Create GitHub Release with download links
  github-release:
    name: Create GitHub Release
    needs: [prepare, release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.prepare.outputs.version-tag }}
          name: Release ${{ needs.prepare.outputs.version-tag }}
          body: |
            ## Release ${{ needs.prepare.outputs.version-tag }}

            ### Installation
            ```xml
            <PackageReference Include="YourPackage" Version="${{ needs.prepare.outputs.version }}" />
            ```

            ### What's New
            <!-- Add release notes here -->

            ### Links
            - [NuGet Package](https://www.nuget.org/packages/YourPackage/${{ needs.prepare.outputs.version }})
            - [Documentation](./README.md)
            - [Changelog](./CHANGELOG.md)
          draft: false
          prerelease: false

# Notes:
# 1. The package-version input ensures all packages use the git tag version
# 2. If .csproj has Version=0.1.0 but you tag v0.1.1, it will publish as 0.1.1
# 3. skip-duplicate: true prevents errors if version already exists on NuGet
# 4. Make sure NUGET_API_KEY is set in repository secrets
