name: 'Security Vulnerability Scan'
description: 'Scan .NET projects for known security vulnerabilities'
inputs:
  working-directory:
    description: 'Working directory to scan'
    required: false
    default: '.'
  fail-on-severity:
    description: 'Minimum severity to fail the build (low, moderate, high, critical)'
    required: false
    default: 'moderate'
runs:
  using: 'composite'
  steps:
    - name: Scan for vulnerable packages
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Scanning for vulnerable packages..."
        
        # Run vulnerability scan and capture output
        SCAN_OUTPUT=$(dotnet list package --vulnerable --include-transitive 2>&1 || true)
        echo "$SCAN_OUTPUT"
        
        # Check if any vulnerabilities were found
        if echo "$SCAN_OUTPUT" | grep -q "has no vulnerable packages"; then
          echo "? No vulnerable packages found"
          exit 0
        fi
        
        # Parse severity levels based on input
        FAIL_BUILD=false
        
        case "${{ inputs.fail-on-severity }}" in
          "critical")
            if echo "$SCAN_OUTPUT" | grep -iq "Critical"; then
              echo "? Critical vulnerabilities found"
              FAIL_BUILD=true
            fi
            ;;
          "high")
            if echo "$SCAN_OUTPUT" | grep -iE "(Critical|High)"; then
              echo "? High or Critical vulnerabilities found"
              FAIL_BUILD=true
            fi
            ;;
          "moderate")
            if echo "$SCAN_OUTPUT" | grep -iE "(Critical|High|Moderate)"; then
              echo "? Moderate, High, or Critical vulnerabilities found"
              FAIL_BUILD=true
            fi
            ;;
          "low")
            if echo "$SCAN_OUTPUT" | grep -iE "(Critical|High|Moderate|Low)"; then
              echo "? Vulnerabilities found"
              FAIL_BUILD=true
            fi
            ;;
        esac
        
        if [ "$FAIL_BUILD" = true ]; then
          echo "::error::Security vulnerabilities detected at or above '${{ inputs.fail-on-severity }}' severity level"
          exit 1
        else
          echo "? No vulnerabilities at or above '${{ inputs.fail-on-severity }}' severity level"
          exit 0
        fi
