name: 'Security Vulnerability Scan'
description: 'Scan .NET projects for known security vulnerabilities'
inputs:
  working-directory:
    description: 'Working directory to scan'
    required: false
    default: '.'
  fail-on-severity:
    description: 'Minimum severity to fail the build (low, moderate, high, critical)'
    required: false
    default: 'moderate'
runs:
  using: 'composite'
  steps:
    - name: List vulnerable packages
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Scanning for vulnerable packages..."
        dotnet list package --vulnerable --include-transitive || true
    
    - name: Check for vulnerabilities
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ "${{ inputs.fail-on-severity }}" == "critical" ]; then
          dotnet list package --vulnerable --include-transitive --severity critical
        elif [ "${{ inputs.fail-on-severity }}" == "high" ]; then
          dotnet list package --vulnerable --include-transitive --severity high
        elif [ "${{ inputs.fail-on-severity }}" == "moderate" ]; then
          dotnet list package --vulnerable --include-transitive --severity moderate
        else
          dotnet list package --vulnerable --include-transitive
        fi
